name: Transmission Web UI Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [ 15.x ]
    steps:
      - uses: actions/checkout@main

      - name: switch branch
        run: |
          git checkout -b release
          rm -rf ./dist

      - name: install dependencies
        run: npm install

      - name: build
        run: npm run build

      - name: rm map
        run: rm -rf ./dist/js/*.map

      - name: push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./dist
          git commit -m 'auto build'
          git push -f origin release
